# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_resource', '0002_auto_20200306_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(blank=True, db_column='file', null=True, upload_to='', verbose_name='Fichier')),
                ('resource', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_resource.Resource')),
            ],
            options={
                'verbose_name': 'Ressource magasin',
                'verbose_name_plural': 'Ressources magasin',
            },
        ),
    ]
